import type { Metadata } from "next";
import { Chakra } from "./chakra";
import { Header } from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Chakra>
          <Header />
          {children}
        </Chakra>
      </body>
    </html>
  );
}
